chinesseRestaurant/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from . import views

app_name = 'chinesseRestaurant'

urlpatterns = [
    path('', views.covidWarning, name='covidWarning'),
    re_path('home/', views.home, name='home'),
    path('customerView/', views.customerView, name='customerView'),
    # path('signup/', views.signup, name='signup'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('foods/', views.item_list, name='item_list'),
    path('foods/<slug:category_slug>/', views.item_list,
         name='item_list'),
    path('orderNow/', views.order_now, name='order_now'),
    path('menu/', views.menu, name='menu'),
    path('edit/', views.edit, name='edit'),
    path('edit_delivery', views.editDeliveryPref, name="editDeliveryPref"),

]

groupProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chinesseRestaurant.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chinesseRestaurant/models.py
import random
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                unique=True)
    date_of_birth = models.DateField(blank=True, null=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d',
                              blank=True)
    streetNum = models.CharField(max_length=25)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=5)

    def __str__(self):
        return f'Profile for user {self.user.username}'


def create_new_ref_number():
    return str(random.randint(100000, 999999))


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True,
                            default='someValue')

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('chinesseRestaurant:item_list',
                       args=[self.slug])


class Item(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='items',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, default='someValue')
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('chinesseRestaurant:item_list',
                       args=[self.id, self.slug])


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)


class Order(models.Model):
    id = models.CharField(
        primary_key=True,
        max_length=6,
        blank=True,
        editable=False,
        unique=True,
        default=create_new_ref_number()
    )
    orderQty = models.CharField(max_length=100)
    order_date = models.DateTimeField(auto_now=True)
    deliveryChoices = (
        ('delivery', 'Delivery'),
        ('pickup', 'Pickup')
    )

    customer = models.ForeignKey(Profile, db_column="Profile", on_delete=models.CASCADE)

    deliveryPref = models.CharField(max_length=10,
                                    choices=deliveryChoices,
                                    default='pickup')

    class Meta:
        ordering= ('id',)
        managed=True


    def __str__(self):
        """String representation for an order object"""
        return f'{self.id}'

chinesseRestaurant/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'image', 'streetNum', 'city', 'state', 'zipcode')

class DeliveryEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('streetNum', 'city', 'state', 'zipcode')

class SignUp(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='')
    last_name = forms.CharField(max_length=30, required=True, help_text='Optional.')
    phoneNumber = forms.CharField(max_length=10, help_text='', required=True,
                                  widget=forms.TextInput(attrs={'placeholder': 'Phone Number'}))
    street_number = forms.CharField(max_length=20, help_text='', required=True,
                                    widget=forms.TextInput(attrs={'placeholder': 'Street Number'}))
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name','last_name',  'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

chinesseRestaurant/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.contrib import messages
from .models import Item, Order, Category, Profile


def item_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()

    items = Item.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        items = items.filter(category=category)

    return render(request,
                  'items/list.html',
                  {'category': category,
                   'categories': categories,
                   'items': items})


# Create your views here.
def home(request):
    num_orders = Order.objects.all()
    context = {
        'num_orders': num_orders
    }
    # Render the html template home.html with the data in the context variable
    return render(request, 'home.html', context=context)


def order_now(request):
    return render(request, 'order_now.html')


def covidWarning(request):
    return render(request, 'covidPrec.html')


def menu(request):
    return render(request, 'menu.html')


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'home.html')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'Registration/login.html', {'form': form})


from django.contrib.auth.decorators import login_required


@login_required
def customerView(request):
    return render(request, 'account/base.html')


from .forms import UserEditForm, ProfileEditForm


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated '
                                      'successfully')
            return render(request, 'account/base.html')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(
            instance=request.user.profile)
    return render(request,
                  'account/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


from .forms import LoginForm, UserRegistrationForm


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request,
                          'Registration/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'Registration/register.html',
                  {'user_form': user_form})


# Create a view that allows user to edit delivery preferences
from .forms import DeliveryEditForm


@login_required
def editDeliveryPref(request):
    if request.method == 'POST':
        profile_form = DeliveryEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Delivery Preferences Updated '
                                      'successfully')
            return render(request, 'account/base.html')
        else:
            messages.error(request, 'Error updating your delivery preferences')
    else:
        profile_form = DeliveryEditForm(
            instance=request.user.profile)
    return render(request,
                  'account/edit_delivery.html',
                  {
                      'profile_form': profile_form})

chinesseRestaurant/templates/covidPrec.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>COVID AGREEMENT BUTTON</title>
    <link rel="stylesheet" href="../static/css/COVID.css">
</head>
<body>
<header>
    <div id="sign_up_button">
                <a href="{% url 'chinesseRestaurant:register' %}">Signup</a>

            </div>
    <div>
        <div id="title">Hello Customer!</div>
        <div id="titlebottom">
            Welcome to our restaurant! We are committed to providing the best foods and the best service for you.
            Hope you can enjoy our foods and service! Because of the COVID pandemic, we only serve pick-up now.
            Sorry for the inconvenience! Please click the agree button to agree our COVID agreement
            and then you can order your foods. Stay safe and have a good day!
        </div>

        <div id="sign_up">
            <div>JOIN US NOW</div>
            <div>GET $10 OFF</div>

        </div>
    </div>
</header>

<div id ="button">
<a href="javascript:">Agree!</a>
<a href="{% url 'chinesseRestaurant:home' %}">Agree!</a>
</div>


</body>
</html>

chinesseRestaurant/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="../static/css/main.css">
    <title>Chinese Spicy Flavor</title>
    <style>
    </style>
</head>

<body>
<ul class="nav navbar-nav">
    <a href="{% url 'chinesseRestaurant:item_list' %}">Foods</a>
    <a href="{% url 'chinesseRestaurant:home' %}">Home</a>
    <a href="{% url 'chinesseRestaurant:home' %}">About</a>
    <a href="{% url 'chinesseRestaurant:home' %}">Contact</a>
    <a href="{% url 'chinesseRestaurant:menu' %}">Menu</a>
    <a href="{% url 'chinesseRestaurant:order_now' %}">Order Now</a>

</ul>


<ul class="secure-nav">
    <a href="{% url 'chinesseRestaurant:register' %}">Sign Up</a>
    <a href="{% url 'chinesseRestaurant:user_login' %}">Login</a>
</ul>
<div id="banner">

    <h1>Welcome to Chinese Spicy Flavor</h1>
</div>

<div id="logo">
    <img src="{% static "images/logo1.jpg" %}" alt="panda"/>
</div>


</body>
</html>

chinesseRestaurant/templates/menu.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Menu</title>
</head>


<body>
    <div class="page-container">
        <p>Please choose from below options.</p>
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-6">
                <img src="{% static "images/Entrees.jpg" %}" alt="Entrees"/>
                <div class="caption">
                    <h2>Entrees</h2>
                    <p>Choose the sides and drink with your entree and make your own platters.</p>
                    <p><a class="btn btn-primary" href="{% url 'crm:entrees_item' %}"
                                         role="button">View
                                       details &raquo;</a></p>
                </div>
            </div>
            <div class="col-md-6">
                <img src="{% static "images/Sides.jpg" %}" alt="Sides"/>
                <div class="caption">
                    <h2>Sides</h2>
                    <p>Stimulate your appetite with best appetizer.</p>
                    <p><a class="btn btn-primary" href="{% url 'crm:sides_item' %}"
                                         role="button">View
                                       details &raquo;</a></p>
                </div>
            </div>
            <div class="col-md-6">
                <img src="{% static "images/Drinks.jpg" %}" alt="Drinks"/>
                <div class="caption">
                    <h2>Drinks</h2>
                    <p>Match your entree with the choice of your fruit drinks.</p>
                    <p><a class="btn btn-primary" href="{% url 'crm:drinks_item' %}"
                                         role="button">View
                                       details &raquo;</a></p>
                </div>
            </div>
            <div class="col-md-6">
                <img src="{% static "images/Desserts.jpg" %}" alt="Desserts"/>
                <div class="caption">
                    <h2>Desserts</h2>
                    <p>Grab your favorite chinese desserts with fruit flavors.</p>
                    <p><a class="btn btn-primary" href="{% url 'crm:desserts_item' %}"
                                         role="button">View
                                       details &raquo;</a></p>
                </div>
            </div>


        </div>

    </div>

</body>
</html>

chinesseRestaurant/templates/order_now.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Now</title>
</head>
<body>
    <h1> You don't need to sign up to order the food </h1>
    <p> You can just order the food from this by selecting the items you want to order </p>
</body>
</html>

chinesseRestaurant/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>